version: "3.0"

services:
  mysql:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: timeguess
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "9090:80"

  spring-backend:
    depends_on:
      - "mysql"
    build:
      context: backend
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ports:
      - "8080:8080"

  angular-client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "80:80"
