
INSERT INTO user(ID,USERNAME,PASSWORD,ROLE) VALUES(0,'admin','$2y$12$CMRQdtQWUxUGOUVAyf.DGOYsBUHtlX55vXA2pUMLCSmiKEkObV4UG','ADMIN')
INSERT INTO category(ID, CATEGORY) VALUES (0, 'Deutschland')
INSERT INTO expression(ID, EXPRESSION, CATEGORY_ID) VALUES (0,'Bundestag',0)
INSERT INTO completed_game_team(ID, NUMBER_OF_GUESSED_EXPRESSIONS, NUMBER_OF_WRONG_EXPRESSIONS, SCORE) VALUES (0,20,5, 40)
INSERT INTO completed_game_team_players(COMPLETED_GAME_TEAM_ID, PLAYERS_ID) VALUES (0,0)
INSERT INTO completed_game(ID, END_TIME, START_TIME, CATEGORY_ID) VALUES (0, '2020-12-14 18:36:14.1', '2020-12-14 18:52:14.1', 0)
INSERT INTO completed_game_attended_teams(COMPLETED_GAME_ID, ATTENDED_TEAMS_ID) VALUES (0,0)
INSERT INTO RASPBERRYID(ID) VALUES ('TESTRASPIID')
